### ISSUE TITLE
Paper autogrow textarea update is mis-documented

### ISSUE THREAD

**Issue by jshortall** [Polymer/paper-input#181]
paper-autogrow-textarea's "update" function requires the textarea to be passed in as an argument and this isn't documented on the component page. 

Took me a little while to figure this out and want to pass it on! 

Thanks

**Comment by notwaldorf** [comment]
This was fixed in https://github.com/Polymer/paper-input/pull/167, but I'm not sure why the docs haven't pulled the change with the last release. Maybe @arthurevans knows?

**Comment by arthurevans** [comment]
Yep, it was because we didn't tag a release. The doc site pulls elements in using bower to build the API docs, so no new release == no updated docs. Honestly, I didn't realize this myself until a week or so ago.

Hoping to push the web site today with updated element docs for 0.5.x and new docs for 0.9.

**Comment by arthurevans** [comment]
Updated docs are live, closing.
