### ISSUE TITLE
input values are not recognized by native form when Polymer.dom = 'shadow'

### ISSUE THREAD

**Issue by vimalraj-a** [Polymer/paper-input#202]
native form tag not recognize the paper-input as input type when submitting form with Polymer forced to use shadow dom by setting global configuration 
`window.Polymer.dom = 'shadow'`

 [JSbin link](http://jsbin.com/fateko/edit?html,js,output)

**Comment by notwaldorf** [comment]
That is correct -- the native form element only looks at `<input>` elements, and ignores everything else. In the shady DOM, the internal `<input>` element is visible to the form, however, in the shadow DOM it is not, because of encapsulation.

If you want to use custom elements with a form, you need to use `iron-form`: https://elements.polymer-project.org/elements/iron-form?view=demo:demo/index.html&active=iron-form
